version: '3'
services:
  wpsnapshots:
    image: 10up/wpsnapshots
    volumes:
      - "./config/wpsnapshots:/wpsnapshots"
      - "./wordpress:/var/www/html"

networks:
  default:
    external:
      name: dev
