version: '3'
services:
  mysql:
    image: mysql:5
    volumes:
      - "./data/db:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
  wpsnapshots:
    image: 10up/wpsnapshots
    depends_on:
      - mysql
    volumes:
      - "./config/wpsnapshots:/wpsnapshots"
      - "./wordpress:/var/www/html"
