config create:
  dbhost: main_db
  dbuser: root
  dbpass:
  extra-php: |
    define( 'DISALLOW_FILE_EDIT', true );
    define( 'WP_DEBUG', true );
    define( 'WP_DEBUG_LOG', true );
    define( 'SAVEQUERIES', true );
    define( 'COOKIE_DOMAIN', $_SERVER['HTTP_HOST'] );
    define( 'WP_CACHE_KEY_SALT', NONCE_SALT );
    $_SERVER['HTTPS'] = 'on';
    $_SERVER['SERVER_NAME'] = $_SERVER['SERVER_NAME'] ?: 'localhost';
    $memcached_servers = [ [ 'main_memcached', 11211 ] ];
