config create:
  dbhost: main_db
  dbuser: root
  dbpass:
  extra-php: |
    define( 'DISALLOW_FILE_EDIT', true );
    define( 'WP_DEBUG', true );
    define( 'SAVEQUERIES', true );
    define( 'COOKIE_DOMAIN', $_SERVER['HTTP_HOST'] );
    $_SERVER['HTTPS'] = 'on';
    $_SERVER['SERVER_NAME'] = $_SERVER['SERVER_NAME'] ?: 'localhost';
    $memcached_servers = [ [ 'main_memcached', 11211 ] ];
